-- SUPPRIMER LA BASE DE DONNEES SI ELLE EXISTE
DROP DATABASE IF EXISTS employes;

-- CREATION DE LA BASE DE DONNEES
CREATE DATABASE employes;

-- UTILISATION DE LA BASE DE DONNEES
USE employes;

-- CREATION DES TABLES
CREATE TABLE dept
(
	deptno TINYINT NOT NULL,
    dname VARCHAR(50) NOT NULL,
    loc VARCHAR(30) NOT NULL,
    CONSTRAINT pk_deptno PRIMARY KEY (deptno)
);

CREATE TABLE emp
(
	empno SMALLINT NOT NULL,
    ename VARCHAR(50) NOT NULL,
    job VARCHAR(30) NOT NULL,
    mgr SMALLINT,
    hiredate DATE NOT NULL,
    sal FLOAT,
    comm SMALLINT,
    CONSTRAINT pk_empno PRIMARY KEY (empno),
    deptno TINYINT -- FOREIGN KEY
);
/*
-- AJOUTERCLES ETRANGERES
ALTER TABLE emp
	ADD CONSTRAINT fk_temp_mgr FOREIGN KEY (mgr) REFERENCES emp(empno),
    ADD CONSTRAINT fk_emp_deptno FOREIGN KEY (deptno) REFERENCES dept(deptno);biblio